### ISSUE TITLE
2019年07月加载失败，是不是版本落后了！

### ISSUE THREAD

**Issue by zainbeau** [shellvon/zh-downloader#14]

**Comment by shellvon** [comment]
请问一下"加载失败"是什么意思？ @zainbeau 我刚看了一下暂时没有发现什么问题

**Comment by zainbeau** [comment]
额。刚开始提示我登录方式有问题，加载视频失败。但是的我知乎账号一直自动登录。看到你回复后，卸载重新安装一次又恢复。谢谢哈。

**Comment by shellvon** [comment]
@zainbeau 感谢反馈，今日抽空看了一下之后发现确实因为太久没更新有BUG了。 目前分享视频显示404，可以参见这里: #15 。我将尽快处理这个问题，如果您有发现其他问题也请及时反馈给我，谢谢您的支持。
