### ISSUE TITLE
mux.js duration 问题

### ISSUE THREAD

**Issue by Momo707577045** [shellvon/zh-downloader#24]
从 mux.js issues 来，还期盼贵项目解决了 duration 问题，😂

**Comment by Momo707577045** [comment]
hls.js 能正确解析时长，但是内置方法，抽取不出来。
可以从这里做实验验证 https://segmentfault.com/a/1190000025182822

**Comment by shellvon** [comment]
@Momo707577045  很遗憾，我之前也在等 mux.js 给我答复，但他们迟迟没有相关进展，所以我换成了 `mpegts_to_mp4` ，能正常处理，加之目前的知乎从 `m3u8` 格式换成 `mp4` 之后，我就完全没研究了，现在更是没有时间和精力了。

**Comment by Momo707577045** [comment]
mux.js 持续时间的问题，我通过添加 duraion 配置项的形式实现了。
这是我的 fork https://github.com/Momo707577045/mux.js
给他们项目提 PR 了
有兴趣可以了解一下
另外，感谢你的答复 (*￣︶￣)
