### ISSUE TITLE
扩展被标记不安全

### ISSUE THREAD

**Issue by zhoufenfens** [shellvon/zh-downloader#31]
您好，扩展因为被谷歌标记成不安全，搜不到这个页面了，这个是什么原因呢，最近有计划更新吗

**Comment by shellvon** [comment]
不好意思，最近一直没有看邮箱。 该扩展因为**违规**使用了权限导致被下架了。

> 违规行为：请求但不使用以下权限：
> notifications

晚些日子我更新一下配置应该就可以了。
